"""add trade_no to credit_transactions

Revision ID: b48a6eafdfd2
Revises: 1f2bb8489b5e
Create Date: 2026-04-24 01:07:55.642110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48a6eafdfd2'
down_revision: Union[str, Sequence[str], None] = '1f2bb8489b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 先加列为 nullable
    op.add_column('credit_transactions', sa.Column('trade_no', sa.String(length=64), nullable=True))
    # 回填已有数据
    op.execute("UPDATE credit_transactions SET trade_no = 'TX_' || type || '_' || to_char(created_at, 'YYYYMMDDHH24MISS') || '_' || substr(md5(id::text), 1, 8) WHERE trade_no IS NULL")
    # 设为 NOT NULL + unique
    op.alter_column('credit_transactions', 'trade_no', nullable=False, type_=sa.String(length=64))
    op.create_unique_constraint(None, 'credit_transactions', ['trade_no'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credit_transactions', type_='unique')
    op.drop_column('credit_transactions', 'trade_no')
    # ### end Alembic commands ###
