"""add reduction tables

Revision ID: c6ba1a447bfb
Revises: c7a1f3e2d8b4
Create Date: 2026-04-24 03:28:59.621488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ba1a447bfb'
down_revision: Union[str, Sequence[str], None] = 'c7a1f3e2d8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reduction_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detect_mode', sa.String(length=10), nullable=False),
    sa.Column('style', sa.String(length=20), nullable=False),
    sa.Column('full_reconstruct', sa.Boolean(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('reduced_text', sa.Text(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_credits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reduction_paragraphs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('is_heading', sa.Boolean(), nullable=False),
    sa.Column('has_formula', sa.Boolean(), nullable=False),
    sa.Column('has_code', sa.Boolean(), nullable=False),
    sa.Column('detection_result', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('needs_processing', sa.Boolean(), nullable=False),
    sa.Column('rewrite_aggressive', sa.Text(), nullable=True),
    sa.Column('rewrite_conservative', sa.Text(), nullable=True),
    sa.Column('user_choice', sa.String(length=20), nullable=True),
    sa.Column('manual_text', sa.Text(), nullable=True),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['reduction_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reduction_paragraphs')
    op.drop_table('reduction_tasks')
    # ### end Alembic commands ###
